name: Blazor

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-test:
    runs-on: windows-2025
    defaults:
      run:
        shell: pwsh
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: '10.0.x'

      - name: Start ASP.NET app
        shell: pwsh
        run: |
          # Launch the app in background and redirect logs
          Start-Process "dotnet" `
            -ArgumentList "run --project samples\basic\BlazorTests\BlazorTests.csproj --urls http://localhost:5162" `
            -RedirectStandardOutput app.log `
            -RedirectStandardError app.log

      - name: Wait for ASP.NET app
        shell: pwsh
        run: |
          for ($i=0; $i -lt 20; $i++) {
            try {
              $response = Invoke-WebRequest http://localhost:5162/ -UseBasicParsing
              Write-Host "Status Code: $($response.StatusCode)"
              Write-Host "Headers:"
              $response.Headers.GetEnumerator() | ForEach-Object { Write-Host "$($_.Name): $($_.Value)" }
              Write-Host "Content:"
              Write-Host $response.Content
              break
            } catch {
              Write-Host "Waiting for app... Error: $($_.Exception.Message)"
              Start-Sleep -Seconds 5
            }
          }

      - name: Show ASP.NET logs
        shell: pwsh
        run: Get-Content app.log -Tail 50

      - name: Start test server and run tests
        run:
          # start the test server, in charge or controlling the client app and reporting the test results
          dotnet run --project samples/basic/AppTester --run-settings ./.github/workflows/browser.json --report-trx --no-tcp

      - name: Publish results
        uses: dorny/test-reporter@v2.2.0
        with:
          name: test-results
          path: ./samples/basic/AppTester/out/TestResults/*.trx
          reporter: dotnet-trx