name: Blazor

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-test:
    runs-on: windows-2025
    defaults:
      run:
        shell: pwsh
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: '10.0.x'

      - name: Publish client app and tools
        run: |
          dotnet restore samples/basic/BlazorTests/BlazorTests.csproj
          dotnet publish samples/basic/BlazorTests/BlazorTests.csproj -c Release
          dotnet tool install --global dotnet-serve

      - name: Start test server and run tests
        run: |
          # run the client app
          $args = "serve -d samples/basic/BlazorTests/bin/Release/net10.0/publish/wwwroot -p 5080"
          Start-Process dotnet -ArgumentList $args -NoNewWindow -PassThru

          # launch the client app in a chrome headless instance
          Write-Host "Launching Chrome headless..."
          $chromeArgs = @(
            "--headless=new",           # Run without UI (Vital for CI)
            "--disable-gpu",            # Prevent rendering issues
            "--no-sandbox",             # Required for some containerized environments
            "--enable-logging",         # Enable internal chrome logging
            "--v=1",                    # Verbosity level
            "http://localhost:5080/"    # Your URL
          )
          $browser = Start-Process chrome -ArgumentList $chromeArgs -PassThru

          # start test server and run tests
          dotnet run --project samples/basic/AppTester --run-settings ./.github/workflows/browser.json --report-trx --no-tcp

      - name: Publish results
        uses: dorny/test-reporter@v2.2.0
        with:
          name: test-results
          path: ./samples/basic/AppTester/out/TestResults/*.trx
          reporter: dotnet-trx