name: MAUI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-ios-test:
    runs-on: macos-15-intel
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.1
        with:
          dotnet-version: '10.0.x'

      - name: Select Xcode 26.1
        run: sudo xcode-select -s /Applications/Xcode_26.1.1.app

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Setup MAUI
        run:
          dotnet workload install maui

      - name: Select simulator UDID
        run: |
          UDID=$(xcrun simctl list devices | grep "iPhone 17 Pro" | grep -oE '[0-9A-F-]{36}' | head -n1)
          echo "UDID=$UDID" >> $GITHUB_ENV

      - name: Boot emulator
        run: |
          xcrun simctl boot "$UDID"
          open -a Simulator.app

      - name: Run tests
        run:
          dotnet run --project samples/basic/AppTester -c Release --report-trx --no-progress --test-groups maui-ios --test-env device="$UDID"

      - name: Publish results
        uses: dorny/test-reporter@v2.2.0
        with:
          name: test-results
          path: samples/basic/AppTester/bin/Release/net10.0/TestResults/*.trx
          reporter: dotnet-trx